#!/usr/bin/env python3
"""Convert the original Side Arms ROM set into Genesis-ready local assets.

Outputs (all ignored by VCS, regenerated from the user's ROMs):
  res/generated/*.bin    binary blobs
  src/gen/data.s         .incbin wrapper with exported symbols
  inc/gen/assets.h       declarations + constants
"""
import json, struct, sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import (Source, ROOT, decode_bgtiles, decode_sprites, decode_chars,
                           bgmap_cells, palette_rgb)
from quantize import to_md, md_word, fit, nearest
from starfield import star_image
import zones as zonecfg

GEN = ROOT / 'res/generated'; SRC = ROOT / 'src/gen'; INC = ROOT / 'inc/gen'
for d in (GEN, SRC, INC):
    d.mkdir(parents=True, exist_ok=True)

symbols = []   # (name, filename, comment)
header = ['/* Generated by tools/build_assets.py from the original ROM set. Do not edit. */',
          '#pragma once', '#include <genesis.h>', '']


def emit(name, data, ctype='u8', comment=''):
    (GEN / f'{name}.bin').write_bytes(data)
    symbols.append(name)
    header.append(f'extern const {ctype} {name}[];  /* {len(data)} bytes {comment}*/')


def be16(vals):
    return b''.join(struct.pack('>H', v & 0xffff) for v in vals)


def tile_bytes(px):
    """8x8 array of 4-bit indices -> 32 bytes Genesis tile."""
    out = bytearray()
    for row in px:
        for x in range(0, 8, 2):
            out.append(((int(row[x]) & 15) << 4) | (int(row[x + 1]) & 15))
    return bytes(out)


src = Source()
main = src.region('maincpu')
lo = main[0x14a37:0x14a37 + 0x400]; hi = main[0x14e37:0x14e37 + 0x400]
ARC = []  # arcade palette as 4-bit rgb tuples
for i in range(1024):
    r, g, b = palette_rgb(lo[i], hi[i])
    ARC.append((r // 17, g // 17, b // 17))
MD = [to_md(c) for c in ARC]

# ---------------------------------------------------------------- stars
# Arcade star colours 0x378..0x37F (colour 0 is black = no visible star).
# Bright colours are reserved: PAL0 idx1-3 (teal, blue, grey), PAL1 idx1-2 (olive, red);
# the dim shades fall back to the nearest reserved colour.
STAR = [MD[0x378 | k] for k in range(8)]
seed0 = [STAR[1], STAR[3], STAR[5]]
seed1 = [STAR[6], STAR[7]]
star_choice = {}
for k in range(1, 8):
    if STAR[k] == (0, 0, 0):
        continue
    opts = [(0, i, c) for i, c in enumerate(seed0)] + [(1, i, c) for i, c in enumerate(seed1)]
    best = min(opts, key=lambda o: sum((a - b) ** 2 for a, b in zip(o[2], STAR[k])))
    star_choice[k] = (best[0], 1 + best[1])
star = star_image(src.region('starfield'))
star_tiles = [bytes(32)]; star_index = {bytes(32): 0}; star_map = []
for cy in range(32):
    for cx in range(64):
        cell = star[cy * 8:cy * 8 + 8, cx * 8:cx * 8 + 8]
        px = np.zeros((8, 8), np.uint8); pal = 0; votes = [0, 0]
        for (y, x) in zip(*np.nonzero(cell >= 0)):
            ch = star_choice.get(int(cell[y, x]))
            if ch: votes[ch[0]] += 1
        pal = 1 if votes[1] > votes[0] else 0
        for (y, x) in zip(*np.nonzero(cell >= 0)):
            ch = star_choice.get(int(cell[y, x]))
            if ch and ch[0] == pal:
                px[y, x] = ch[1]
        tb = tile_bytes(px)
        if tb not in star_index:
            star_index[tb] = len(star_tiles); star_tiles.append(tb)
        star_map.append(star_index[tb] | (pal << 13 if star_index[tb] else 0))
emit('star_tiles', b''.join(star_tiles), comment='stars ')
emit('star_map', be16(star_map), 'u16', '64x32 cells, b13 = PAL1 ')
header.append(f'#define STAR_TILE_COUNT {len(star_tiles)}')

# ---------------------------------------------------------------- background zones
bgt = decode_bgtiles(src.region('bgtiles'))
code, color, flags = bgmap_cells(src.region('bgmap'))
zone_rows = []
for zi, z in enumerate(zonecfg.ZONES):
    x0, y0, w, h = z['rect']
    cells = [(code[r, c], color[r, c]) for r in range(y0, y0 + h) for c in range(x0, x0 + w)]
    metas = sorted(set(cells))
    mid = {m: i for i, m in enumerate(metas)}
    # blocks = each 8x8 subtile of each metatile
    blocks = []
    for (cd, cl) in metas:
        t = bgt[cd]
        for sy in range(4):
            for sx in range(4):
                sub = t[sy * 8:sy * 8 + 8, sx * 8:sx * 8 + 8]
                hist = {}
                for pen, n in zip(*np.unique(sub, return_counts=True)):
                    if pen != 15:
                        c = MD[cl * 16 + int(pen)]; hist[c] = hist.get(c, 0) + int(n)
                blocks.append(hist)
    pals, assign = fit(blocks, 2, 15, fixed=[seed0, seed1])
    tiles = bytearray(); attrs = bytearray(); bi = 0
    for (cd, cl) in metas:
        t = bgt[cd]
        for sy in range(4):
            for sx in range(4):
                sub = t[sy * 8:sy * 8 + 8, sx * 8:sx * 8 + 8]
                p = int(assign[bi]); bi += 1
                lut = {pen: (0 if pen == 15 else 1 + nearest(MD[cl * 16 + pen], pals[p])) for pen in range(16)}
                px = np.vectorize(lut.get)(sub)
                tiles += tile_bytes(px)
                # nametable template: palette + high priority + subtile index; 0 = empty
                idx = sy * 4 + sx
                attrs += struct.pack('>H', 0 if not px.any() else (0x8000 | (p << 13) | idx))
    zmap = [mid[(code[r, c], color[r, c])] | (((flags[r, c] & 1) << 14) | ((flags[r, c] & 2) << 14))
            for r in range(y0, y0 + h) for c in range(x0, x0 + w)]
    palwords = []
    for p in pals:
        palwords += [0] + [md_word(c) for c in p] + [0] * (15 - len(p))
    emit(f'zone{zi}_tiles', bytes(tiles), comment=f'{len(metas)} metatiles x16 ')
    emit(f'zone{zi}_attr', bytes(attrs), 'u16', comment='16 nametable templates per metatile (0 = empty) ')
    emit(f'zone{zi}_map', be16(zmap), 'u16', 'b0-11 meta, b14 hflip, b15 vflip ')
    emit(f'zone{zi}_pal', be16(palwords), 'u16', 'PAL0+PAL1 ')
    zone_rows.append((z['name'], x0, y0, w, h, len(metas)))
    print(f"zone {z['name']}: {len(metas)} metatiles, palettes {[len(p) for p in pals]}")

header.append('typedef struct { u16 x0, y0, w, h, metas; const u8 *tiles; const u16 *tmpl; const u16 *map; const u16 *pal; } Zone;')
header.append(f'#define ZONE_COUNT {len(zone_rows)}')
header.append('extern const Zone zones[ZONE_COUNT];')

# ---------------------------------------------------------------- sprites
spr = decode_sprites(src.region('sprites'))
# raw pens, Genesis 2x2 sprite order (column-major): tiles (0,0),(0,1),(1,0),(1,1) as (x,y)
raw = bytearray()
for n in range(len(spr)):
    for tx in range(2):
        for ty in range(2):
            raw += tile_bytes(spr[n][ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8])
emit('sprite_pens', bytes(raw), comment='2048 x 128, arcade pens 0-15 ')
usage = json.loads((ROOT / 'tools/sprite_palette_usage.json').read_text()) if (ROOT / 'tools/sprite_palette_usage.json').exists() else {}

# ---------------------------------------------------------------- player tables
# (before the sprite bank: it lists every sprite the player module draws)
import subprocess
subprocess.run([sys.executable, str(ROOT / 'tools/build_player.py')], check=True)

# ---------------------------------------------------------------- sprite pattern set
# Every (code, colour) pair the game can show. Pairs come from the extracted behaviour
# tables (templates, motion scripts, metasprite frames, player data); composites are
# expanded (2x2: c, c+1, c+8, c+9). Missing pairs fall back to a runtime remap.
def _walk(o, out):
    if isinstance(o, dict):
        code = o.get('code'); col = o.get('color', o.get('colour'))
        if isinstance(code, int) and isinstance(col, int):
            out.add((code & 0x7FF, col & 15))
        for v in o.values():
            _walk(v, out)
    elif isinstance(o, list):
        for v in o:
            _walk(v, out)
pairs = set()
for name in ('metasprites.json', 'spawns.json', 'player.json', 'player_sprites.json'):
    f = GEN / name
    if f.exists():
        _walk(json.loads(f.read_text()), pairs)
expanded = set()
for code, col in pairs:
    for add in (0, 1, 8, 9):
        expanded.add(((code + add) & 0x7FF, col))
# Usage list observed in MAME runs (tools/sprite_pairs.json, metadata only):
# include each observed pair's whole 16-code page in that colour.
obs = ROOT / 'tools/sprite_pairs.json'
if obs.exists():
    for k in json.loads(obs.read_text()):
        code, col = k & 0x7FF, k >> 11
        for c in range(code & ~15, (code & ~15) + 16):
            expanded.add((c, col))
keys = sorted(c | (col << 11) for c, col in expanded)
keyset = set(keys)
# 32x32 composites (cells c, c+1, c+8, c+9), built for every 2x2-aligned code (c & 9 == 0)
# whose four cells are in the set, plus any pair the behaviour tables name.
big_set = {(c, col) for c, col in pairs if all((((c + a) & 0x7FF) | (col << 11)) in keyset for a in (0, 1, 8, 9))}
for k in keys:
    c, col = k & 0x7FF, k >> 11
    if not (c & 9) and all((((c + a) & 0x7FF) | (col << 11)) in keyset for a in (1, 8, 9)):
        big_set.add((c, col))
big_keys = sorted(c | (col << 11) for c, col in big_set)

# ---------------------------------------------------------------- sprite palettes
# PAL2/PAL3 are fitted to the patterns actually drawn (pixel histograms of every
# 16x16 cell and 32x32 composite, weighted by how often the arcade colour is used)
# and each pattern then uses whichever palette represents it better. Both palettes
# also carry seeded HUD/text colours (window-plane text picks PAL2 or PAL3 per colour).
TXT_SEED3 = [to_md(c) for c in [(1, 1, 1), (15, 15, 15), (15, 0, 0), (0, 12, 15), (0, 0, 14), (14, 14, 0)]]
TXT_SEED2 = [to_md(c) for c in [(0, 14, 0), (15, 10, 0), (15, 0, 15), (0, 6, 10), (7, 6, 0), (12, 12, 0)]]
def _hist(codes, col):
    h = {}
    for code in codes:
        pens, n = np.unique(spr[code], return_counts=True)
        for pen, cnt in zip(pens, n):
            if pen != 15:
                c = MD[512 + col * 16 + int(pen)]; h[c] = h.get(c, 0) + int(cnt)
    w = max(1, usage.get(str(col), 1)) / 256.0
    return {c: v * w for c, v in h.items()}
blocks = [_hist([k & 0x7FF], k >> 11) for k in keys]
blocks += [_hist([((k & 0x7FF) + a) & 0x7FF for a in (0, 1, 8, 9)], k >> 11) for k in big_keys]
spals, assign = fit(blocks, 2, 15, fixed=[TXT_SEED2, TXT_SEED3])
small_pal = [int(a) for a in assign[:len(keys)]]
big_pal = [int(a) for a in assign[len(keys):]]
# per arcade colour fallback (runtime remap, bosses, front end): the palette that fits its 15 colours best
from quantize import _dist as _qdist
sprite_lut = bytearray(); col_pal = []
for c in range(16):
    cols = [MD[512 + c * 16 + p] for p in range(15)]
    errs = [float(_qdist(cols, np.array(spals[k])).min(1).sum()) for k in range(2)]
    col_pal.append(int(np.argmin(errs)))
for c in range(16):
    pal = spals[col_pal[c]]
    sprite_lut += bytes([0 if p == 15 else 1 + nearest(MD[512 + c * 16 + p], pal) for p in range(16)])
sprite_lut += bytes(col_pal)    # 16 bytes: genesis palette (0/1 -> PAL2/PAL3)
emit('sprite_lut', bytes(sprite_lut), comment='16 colors x16 pens + 16 pal sel ')
pair = bytearray()
for c in range(16):
    pl = sprite_lut[c * 16:c * 16 + 16]
    for b in range(256):
        pair.append((pl[b >> 4] << 4) | pl[b & 15])
emit('sprite_pair_lut', bytes(pair), comment='16 colours x 256 ')
swords = []
for p in spals:
    swords += [0] + [md_word(c) for c in p] + [0] * (15 - len(p))
emit('sprite_pal', be16(swords), 'u16', 'PAL2+PAL3 ')
_lut_cache = {}
def pen_lut(col, p):
    if (col, p) not in _lut_cache:
        _lut_cache[(col, p)] = [0 if q == 15 else 1 + nearest(MD[512 + col * 16 + q], spals[p]) for q in range(16)]
    return _lut_cache[(col, p)]
def convert(code, col, p):
    pl = pen_lut(col, p)
    return bytes((pl[b >> 4] << 4) | pl[b & 15] for b in raw[code * 128:code * 128 + 128])

# ---------------------------------------------------------------- sprite pattern bank
bank = bytearray()
index = [0] * 32768
for i, k in enumerate(keys):
    bank += convert(k & 0x7FF, k >> 11, small_pal[i])
    index[k] = (i + 1) | (small_pal[i] << 15)       # bit 15: PAL3
emit('spr_bank_keys', be16(keys), 'u16', 'sorted code | colour << 11 ')
emit('spr_bank', bytes(bank), comment='pre-converted 16x16 patterns ')
header.append(f'#define SPR_BANK_COUNT {len(keys)}')
print('sprite bank:', len(keys), 'patterns', len(bank) // 1024, 'KB')
emit('spr_bank_index', be16(index), 'u16', 'code | colour << 11 -> spr_bank entry + 1, b15 = PAL3 ')
# 32x32 composites pre-interleaved in the Genesis 4x4 sprite order (column-major: each
# 32-px column = top cell column + bottom cell column): one 512-byte DMA per upload.
# All four cells use the block's own palette choice.
big = bytearray()
big_index = [0] * 32768
for i, k in enumerate(big_keys):
    code, col, p = k & 0x7FF, k >> 11, big_pal[i]
    tl, tr, bl, br = (convert((code + a) & 0x7FF, col, p) for a in (0, 1, 8, 9))
    for colx in range(4):
        top, bot = (tl, bl) if colx < 2 else (tr, br)
        h = (colx & 1) * 64
        big += top[h:h + 64] + bot[h:h + 64]
    big_index[k] = (len(big) // 512) | (p << 15)
emit('spr_big_index', be16(big_index), 'u16', 'code | colour << 11 -> spr_big block + 1, b15 = PAL3 ')
emit('spr_big', bytes(big), comment='pre-interleaved 32x32 composites, 512 bytes each ')
print('sprite 32x32 blocks:', len(big_keys), len(big) // 1024, 'KB')

# ---------------------------------------------------------------- text layer font
# Chars: 2bpp, pen 3 transparent. Stored as Genesis 4bpp with nibble = pen + 1
# (so 0 never appears); txt_lut[colour][byte] maps two nibbles to PAL3 indices.
chars = decode_chars(src.region('fgtiles'))
font = bytearray()
for n in range(len(chars)):
    font += tile_bytes(chars[n] + 1)
emit('font_pens', bytes(font), comment='1024 chars, nibble = pen+1 ')
emit('font_blank', bytes(1 if (chars[n] == 3).all() else 0 for n in range(len(chars))), comment='1 = fully transparent char ')
import numpy as _np
from quantize import _dist
tlut = bytearray(); tpal = bytearray()
for c in range(64):
    cols = [MD[768 + c * 4 + pen] for pen in range(3)]
    errs = [float(_dist(cols, _np.array(spals[k])).min(1).sum()) for k in range(2)]
    k = int(_np.argmin(errs)); tpal.append(k)
    m = [0] * 16
    for pen in range(3):
        m[pen + 1] = 1 + nearest(cols[pen], spals[k])
    for b in range(256):
        tlut.append((m[b >> 4] << 4) | m[b & 15])
emit('txt_lut', bytes(tlut), comment='64 colours x 256 ')
emit('txt_pal', bytes(tpal), comment='per text colour: 0 = PAL2, 1 = PAL3 ')

# ---------------------------------------------------------------- levels + terrain
import subprocess
subprocess.run([sys.executable, str(ROOT / 'tools/build_levels.py')], check=True)
# front end / HUD data (needs the text font above): tools/build_frontend.py
subprocess.run([sys.executable, str(ROOT / 'tools/build_frontend.py')], check=True)
subprocess.run([sys.executable, str(ROOT / 'tools/build_enemies.py')], check=True)
# bosses (needs sprite_lut/sprite_pens and the zone palettes above): tools/build_bosses.py
subprocess.run([sys.executable, str(ROOT / 'tools/build_bosses.py')], check=True)
emit('terrain', (GEN / 'terrain.bin').read_bytes(), comment='256x256 bits, 16x16 world cells ')

# ---------------------------------------------------------------- colour mode "VIVID"
# Optional display mode (front-end COLOR option): every Genesis colour is mapped to a
# more saturated, slightly brighter one. Index = BBBGGGRRR (3 bits each, see palette.c).
# Neutral greys stay neutral and nothing gets darker.
import colorsys
vivid = []
for w in range(512):
    r, g, b = (w & 7), (w >> 3) & 7, (w >> 6) & 7
    h, sat, v = colorsys.rgb_to_hsv(r / 7, g / 7, b / 7)
    if sat > 0.05:
        sat = min(1.0, sat * 1.40)
    v = min(1.0, v * 1.15) if v > 0 else 0
    nr, ng, nb = colorsys.hsv_to_rgb(h, sat, v)
    q = [max(o, int(round(n * 7))) if sat <= 0.05 else int(round(n * 7)) for n, o in ((nr, r), (ng, g), (nb, b))]
    if max(q) < max(r, g, b):
        q = [r, g, b]
    vivid.append((q[2] << 9) | (q[1] << 5) | (q[0] << 1))
emit('vivid_lut', be16(vivid), 'u16', 'Genesis colour >> 1 -> vivid colour ')

# ---------------------------------------------------------------- outputs
lines = ['/* Generated by tools/build_assets.py. */', '.section .rodata', '.align 2']
for name in symbols:
    # 512-byte alignment: blobs that are DMA'd in 128/512-byte units (sprite patterns, metatiles)
    # must not straddle a 128 KB boundary, which a VDP DMA source cannot cross
    lines += [f'.global {name}', '.balign 512', f'{name}:', f'.incbin "res/generated/{name}.bin"']
(SRC / 'data.s').write_text('\n'.join(lines) + '\n')
zl = ['/* Generated by tools/build_assets.py. */', '#include "gen/assets.h"', 'const Zone zones[ZONE_COUNT] = {']
for zi, (name, x0, y0, w, h, n) in enumerate(zone_rows):
    zl.append(f'    {{{x0}, {y0}, {w}, {h}, {n}, zone{zi}_tiles, zone{zi}_attr, zone{zi}_map, zone{zi}_pal}}, /* {name} */')
zl.append('};')
(SRC / 'zones.c').write_text('\n'.join(zl) + '\n')
(INC / 'assets.h').write_text('\n'.join(header) + '\n')
print('assets:', len(symbols), 'blobs')
