#!/usr/bin/env python3
"""Home-mode parallax tables (docs/parallax.md) -> src/gen/parallax_data.c, inc/gen/parallax_data.h.

Run by tools/build_assets.py after the zones (the far layers and the zone variants they need are
built inside its zone loop with parallax_split.py). Everything here is derived from the ROM set
(star generator, level legs, BG map); nothing is hand-drawn.

Tables:
  * star depth per plane-A row (32 rows of 8 lines): the starfield's own 512x256 image is cut into
    four depth layers by row; dim rows go far, bright rows near.
  * star depth per 16-px screen column (vertical legs with column scroll).
  * column legs: vertical legs that start and end at a camera cut (teleport / section start), where
    column V-scroll can run without stars jumping when the camera turns.
  * BG bands (horizontal legs): rows of distant scenery scrolled slower than the playfield.
"""
import json, sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import Source, ROOT, palette_rgb
from quantize import to_md
from starfield import star_image
import zones as zonecfg

GEN = ROOT / 'res/generated'; SRC = ROOT / 'src/gen'; INC = ROOT / 'inc/gen'
VIEW_X, VIEW_Y = 96, 16                 # camera = arcade scroll + (96, 16) (inc/video.h)
SCREEN_W, SCREEN_H = 320, 224

# Depth speeds in 1/16 of the camera speed (the BG plane moves at 16/16). Arcade stars: 8/16.
STAR_SPEED = [2, 4, 8, 12]
STAR_V_SPEED = 8                        # rows mode: one vertical speed (the arcade's)

levels = json.loads((GEN / 'levels.json').read_text())


def star_rows():
    """depth 0 (far) .. 3 (near) per 8-line row of the star image, by star brightness"""
    src = Source()
    main = src.region('maincpu')
    lo = main[0x14a37:0x14a37 + 0x400]; hi = main[0x14e37:0x14e37 + 0x400]
    md = [to_md(tuple(c // 17 for c in palette_rgb(lo[0x378 | k], hi[0x378 | k]))) for k in range(8)]
    lum = [0.3 * r + 0.59 * g + 0.11 * b for (r, g, b) in md]
    img = star_image(src.region('starfield'))
    score = []
    for r in range(32):
        band = img[r * 8:r * 8 + 8]
        v = [lum[int(k)] for k in band[band >= 0] if lum[int(k)] > 0]
        score.append((np.mean(v) if v else 0.0, len(v), r))
    order = sorted(score)                       # dim -> bright
    depth = [0] * 32
    for i, (_, _, r) in enumerate(order):
        depth[r] = i * 4 // 32
    return depth


def star_cols():
    """20 screen columns of 16 px: a fixed shuffle of the 4 depths, no two neighbours equal"""
    rng = np.random.RandomState(1986)
    for _ in range(1000):
        d = list(rng.permutation([0, 1, 2, 3] * 5))
        if all(d[i] != d[i + 1] for i in range(19)):
            return d
    raise SystemExit('no column shuffle')


def legs():
    """[(section, dir, start_cam, end_cam, cut_before, cut_after)] in camera pixels"""
    out = []
    for s in levels['sections']:
        L = s['legs']
        for i, leg in enumerate(L):
            st = (leg['start'][0] + VIEW_X, leg['start'][1] + VIEW_Y)
            en = (leg['end'][0] + VIEW_X, leg['end'][1] + VIEW_Y)
            adj = lambda a, b: abs(a[0] - b[0]) <= 1 and abs(a[1] - b[1]) <= 1
            cut_b = i == 0 or not adj(L[i - 1]['end'], leg['start'])
            cut_a = i + 1 == len(L) or not adj(leg['end'], L[i + 1]['start'])
            out.append((s['section'], tuple(leg['dir']), st, en, cut_b, cut_a))
    return out


def column_legs():
    """vertical legs bounded by cuts, long enough to show depth, plane B on a 16-px column grid"""
    out = []
    for sec, d, st, en, cb, ca in legs():
        if d[0] != 0 or d[1] == 0 or not (cb and ca):
            continue
        if abs(en[1] - st[1]) < 384 or st[0] % 16:
            continue
        y0, y1 = sorted((st[1], en[1]))
        out.append((sec, st[0], y0, y1))
    return out


def emit_tables(far=None, bands=None):
    far = far or []; bands = bands or []
    rows, cols, cl = star_rows(), star_cols(), column_legs()
    h = ['/* Generated by tools/build_parallax.py from the original ROM set. Do not edit. */',
         '#pragma once', '#include <genesis.h>', '',
         f'#define PAR_STAR_LAYERS {len(STAR_SPEED)}',
         f'#define PAR_STAR_V_SPEED {STAR_V_SPEED}      /* rows mode: vertical star speed, 1/16 camera */',
         'extern const u8 par_star_speed[PAR_STAR_LAYERS];   /* 1/16 of the camera speed */',
         'extern const u8 par_star_row[32];                  /* depth layer of each 8-line plane-A row */',
         'extern const u8 par_star_col[20];                  /* depth layer of each 16-px screen column */',
         'typedef struct { s16 x, y0, y1; } ParColLeg;       /* camera x, camera y range (inclusive) */',
         f'#define PAR_COL_LEGS {len(cl)}',
         'extern const ParColLeg par_col_legs[PAR_COL_LEGS];',
         '/* far layer: plane A shows a periodic texture of a zone (the zone variant has it cut out) */',
         'typedef struct { s16 x0, x1, y; s16 off0; u8 num, den; } ParSeg;   /* off = off0 + (cam_x - x0) * num / den */',
         'typedef struct {',
         '    u16 zone;                   /* zones[] index */',
         '    const u8 *tiles; u16 ntiles; /* far texture tiles */',
         '    const u16 *map; u8 w, h;    /* one period in tiles (tile index relative, attr: palette, flips) */',
         '    s16 rx0, ry0, rx1, ry1;     /* camera rect where plane A must show the texture */',
         '    u8 nseg; const ParSeg *seg; /* horizontal parallax segments (outside: offset 0) */',
         '} ParFar;',
         f'#define PAR_FAR_COUNT {len(far)}',
         'extern const ParFar par_far[];',
         '/* BG band: world cell rows [cy0, cy1] scrolled at their own camera x on a horizontal leg */',
         'typedef struct { u16 zone; s16 cam_y, x0, x1; u8 cy0, cy1; u8 num, den; } ParBand;',
         f'#define PAR_BAND_COUNT {len(bands)}',
         'extern const ParBand par_bands[];',
         ]
    c = ['/* Generated by tools/build_parallax.py from the original ROM set. Do not edit. */',
         '#include "gen/parallax_data.h"', '#include "gen/assets.h"',
         'const u8 par_star_speed[PAR_STAR_LAYERS] = {%s};' % ', '.join(map(str, STAR_SPEED)),
         'const u8 par_star_row[32] = {%s};' % ', '.join(map(str, rows)),
         'const u8 par_star_col[20] = {%s};' % ', '.join(map(str, cols)),
         'const ParColLeg par_col_legs[PAR_COL_LEGS] = {']
    for sec, x, y0, y1 in cl:
        c.append(f'    {{{x}, {y0}, {y1}}},   /* section {sec} */')
    c.append('};')
    for i, f in enumerate(far):
        c.append(f'static const ParSeg far{i}_seg[] = {{')
        for s in f['segs']:
            c.append('    {%d, %d, %d, %d, %d, %d},' % tuple(s))
        c.append('};')
    c.append('const ParFar par_far[] = {')
    for i, f in enumerate(far):
        c.append(f"    {{{f['zone']}, {f['tiles']}, {f['ntiles']}, {f['map']}, {f['w']}, {f['h']}, "
                 f"{f['rect'][0]}, {f['rect'][1]}, {f['rect'][2]}, {f['rect'][3]}, {len(f['segs'])}, far{i}_seg}},"
                 f"   /* {f['name']} */")
    if not far:
        c.append('    {0},')
    c.append('};')
    c.append('const ParBand par_bands[] = {')
    for b in bands:
        c.append('    {%d, %d, %d, %d, %d, %d, %d, %d},   /* %s */' % (tuple(b[:8]) + (b[8],)))
    if not bands:
        c.append('    {0},')
    c.append('};')
    (INC / 'parallax_data.h').write_text('\n'.join(h) + '\n')
    (SRC / 'parallax_data.c').write_text('\n'.join(c) + '\n')
    print(f'parallax: star rows {rows}, column legs {[(s, x, y0, y1) for s, x, y0, y1 in cl]}, '
          f'far layers {len(far)}, bands {len(bands)}')


if __name__ == '__main__':
    far = json.loads((GEN / 'parallax_far.json').read_text()) if (GEN / 'parallax_far.json').exists() else []
    import parallax_split
    emit_tables(far, parallax_split.bands())
