#!/usr/bin/env python3
"""Native level timelines + terrain map from the extracted arcade behaviour data.

Inputs (regenerated from the ROM by tools/extract_levels.py / extract_spawns.py):
  res/generated/levels.json  sections, control ops, terrain bitmap
  res/generated/spawns.json  complete per-section script timeline with the
                             camera position at which each record fires
Outputs: src/gen/level_data.c, inc/gen/level_data.h, res/generated/terrain.bin

Positions are in arcade scroll units (camera = scroll + (96, 16)). An event
fires when the camera reaches its trigger position, in list order, the way
the arcade script fires records (docs/re/levels.md).

Section ends: each section's script closes with a call of the teleport that
opens the next section (B0:$8194-$82CB, listed in the next section's control
ops). It becomes EV_NEXT (the port starts the next section) and keeps its
spawn index so the enemy module's per-section spawn tables stay aligned.
MUSIC events carry the enemy-bullet speed level the arcade loads into $E050
with the music (B0:$80CA-$812F, tables $813C + 8*stage, default difficulty)."""
import json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import Source

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / 'res/generated'
lv = json.loads((GEN / 'levels.json').read_text())
sp = json.loads((GEN / 'spawns.json').read_text())

OPS = ['EV_TELEPORT', 'EV_MUSIC', 'EV_DIR_X', 'EV_DIR_Y', 'EV_RANK', 'EV_BOSS', 'EV_HALT', 'EV_SPAWN', 'EV_NEXT']
MAIN = Source().region('maincpu')            # bank 0 is mapped at $8000 = region offset $8000
DIFFICULTY = 3                               # ~DSW0 & 7 with the MAME default dips (docs/re/objects.md 5)
TELEPORTS = range(0x8194, 0x82CC)            # B0:$8194-$82CB: ld hl,Y / ld (E094),hl / ld hl,X / ld (E092),hl


def bullet_level(sound):
    """B0:$80CA-$812F: stage music $21-$29 / $36 also loads $E050 from table $813C + 8*stage."""
    k = 9 if sound == 0x36 else sound - 0x21
    return MAIN[0x813C + 8 * k + DIFFICULTY] if 0 <= k <= 9 else 0


def teleport_dest(addr):
    """decode ld hl,Y / ld ($E094),hl / ld hl,X / ld ($E092),hl at a B0 teleport entry"""
    b = MAIN[addr:addr + 12]
    assert b[0] == 0x21 and b[3] == 0x22 and b[6] == 0x21 and b[9] == 0x22, hex(addr)
    return b[7] | b[8] << 8, b[1] | b[2] << 8

BOSS_KIND = {'sprite': 0, 'bg_wheel': 1, 'final': 2}

sections = []
for sec, st in zip(lv['sections'], sp['stages']):
    ctrl = {c['ptr']: c for c in sec['control']}
    events = []
    spawn_index = 0
    for e in st['events']:
        if e['kind'] == 'resume_after_boss':
            continue
        ptr = e['script']
        x, y = e['camera']['x'], e['camera']['y']
        c = ctrl.get(ptr)
        if c:
            op = c['op']
            if op == 'teleport':
                events.append(('EV_TELEPORT', x, y, 0, c['x'], c['y'], ptr))
            elif op == 'music':
                events.append(('EV_MUSIC', x, y, c['sound'], 0, bullet_level(c['sound']), ptr))
            elif op in ('dir_x', 'dir_y'):
                d = c['dir']
                events.append(('EV_DIR_X' if op == 'dir_x' else 'EV_DIR_Y', x, y, 0 if d == 0 else (1 if d == 1 else 2), 0, 0, ptr))
            elif op == 'rank':
                events.append(('EV_RANK', x, y, c['base'], 0, 0, ptr))
            elif op == 'boss':
                events.append(('EV_BOSS', x, y, BOSS_KIND.get(c['kind'], 0), int(c['target'], 16), 0, ptr))
            elif op == 'halt':
                events.append(('EV_HALT', x, y, 0, 0, 0, ptr))
            continue
        # everything else spawns enemies/objects; the enemy module owns the
        # per-section spawn table (same index order: tools/build_enemies.py)
        routine = int(e.get('routine', '0'), 16) if 'routine' in e else 0
        if routine in TELEPORTS and e.get('kind') == 'call':
            dx, dy = teleport_dest(routine)
            events.append(('EV_NEXT', x, y, 0, dx, dy, ptr))
        else:
            events.append(('EV_SPAWN', x, y, 0, spawn_index, routine, ptr))
        spawn_index += 1
    sections.append({'n': sec['section'], 'start': sec['start_scroll'], 'events': events, 'spawns': spawn_index})

c = ['/* Generated by tools/build_levels.py from the extracted arcade data. Do not edit. */',
     '#include "gen/level_data.h"', '']
for s in sections:
    c.append(f"static const LevelEvent sec{s['n']}[] = {{")
    for op, x, y, a, b, cc, ptr in s['events']:
        c.append(f'    {{{x}, {y}, {op}, {a}, {b}, {cc}}},   /* B1:${ptr} */')
    c.append('};')
c.append('const LevelSection level_sections[LEVEL_SECTIONS] = {')
for s in sections:
    c.append(f"    {{{s['start'][0]}, {s['start'][1]}, {len(s['events'])}, {s['spawns']}, sec{s['n']}}},")
c.append('};')
(ROOT / 'src/gen/level_data.c').write_text('\n'.join(c) + '\n')

h = ['/* Generated by tools/build_levels.py. Do not edit. */', '#pragma once', '#include <genesis.h>', '',
     'enum { ' + ', '.join(OPS) + ' };',
     '/* x, y: camera trigger (arcade scroll units). a/b/c by op:',
     ' *   TELEPORT b,c = destination   MUSIC a = sound id, c = enemy bullet speed level ($E050)   DIR_X/Y a = 0 stop, 1 +, 2 -',
     ' *   RANK a = base rank   BOSS a = kind (0 sprite, 1 wheel, 2 final), b = arcade routine id',
     ' *   HALT  (stop scrolling until the boss dies)   SPAWN b = index in the section spawn table, c = arcade routine id',
     ' *   NEXT  end of section: the arcade teleports to b,c = the next section start (the port calls level_start) */',
     'typedef struct { u16 x, y; u8 op, a; u16 b, c; } LevelEvent;',
     'typedef struct { u16 start_x, start_y, nevents, nspawns; const LevelEvent *ev; } LevelSection;',
     f'#define LEVEL_SECTIONS {len(sections)}',
     'extern const LevelSection level_sections[LEVEL_SECTIONS];']
(ROOT / 'inc/gen/level_data.h').write_text('\n'.join(h) + '\n')

# terrain: 1 bit per 16x16 world cell, 256x256, row-major, MSB = leftmost
col = lv['collision']
rows = [bytes.fromhex(r) for r in col['rows_hex']]
assert len(rows) == 256 and all(len(r) == 32 for r in rows), (len(rows), len(rows[0]))
(GEN / 'terrain.bin').write_bytes(b''.join(rows))
print('levels:', [(s['n'], len(s['events']), s['spawns']) for s in sections])
