#!/usr/bin/env python3
"""Front-end / HUD data, converted from the original ROM set at build time.

Run by tools/build_assets.py after the text-layer font (font_pens, txt_lut, txt_pal,
font_blank) has been generated. Outputs (all ignored by VCS):
  res/generated/fe_*.bin      tile blobs and scene maps
  src/gen/frontend.s          .incbin wrapper
  src/gen/frontend_data.c     small tables (strings, ranking, demo inputs/scripts)
  inc/gen/frontend.h          declarations

Contents (arcade sources, see docs/frontend.md and docs/re/flow_player.md):
  * SIDE ARMS logo: the 32x8 text-layer block drawn by $0DF5 (string $0EA4, attr $70),
    pre-rendered to deduplicated Genesis tiles + a nametable.
  * Weapon bar glyphs $50-$63 in the four bar colours of $1E7C ($20 none, $25 owned,
    $23/$24 selected flash), streamed per player by hud.c.
  * Background "scenes": the fixed world views shown by the title ($0BD1: scroll $180,0)
    and the Earth intro ($13BC-$153B, 15 scroll positions), rendered from the BG ROMs and
    quantized to PAL0/PAL1 (star colours kept at the indices video.c's starfield uses).
  * Text strings (region warning, ranking, credit screen, intro, HUD messages) decoded
    from their $03BD records, default ranking ($0B34), bonus-life tables ($09EF).
  * Attract demo: recorded inputs (B2:$9600/$9800, $9A00/$9D00, read by B2:$802C) and the
    two demo scroll scripts (B1:$8000 / B1:$8074) simulated into camera-triggered events.
"""
import json, struct, sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import Source, ROOT, decode_chars, decode_bgtiles, bgmap_cells, palette_rgb
from quantize import to_md, md_word, fit, nearest

GEN = ROOT / 'res/generated'; SRC = ROOT / 'src/gen'; INC = ROOT / 'inc/gen'
for d in (GEN, SRC, INC):
    d.mkdir(parents=True, exist_ok=True)

# VRAM tile bases the data is built for (inc/video.h, inc/hud.h)
VRAM_BG_TILE = 160          # scenes use the BG metatile cache region while bg.c is off
BG_CACHE_TILES = 56 * 16

src = Source()
M = src.region('maincpu')
symbols, header = [], ['/* Generated by tools/build_frontend.py from the original ROM set. Do not edit. */',
                       '#pragma once', '#include <genesis.h>', '']
cdata = ['/* Generated by tools/build_frontend.py from the original ROM set. Do not edit. */',
         '#include "gen/frontend.h"', '']


def emit(name, data, ctype='u8', comment=''):
    (GEN / f'{name}.bin').write_bytes(data)
    symbols.append(name)
    header.append(f'extern const {ctype} {name}[];  /* {len(data)} bytes {comment}*/')


def be16(vals):
    return b''.join(struct.pack('>H', v & 0xffff) for v in vals)


def carr(ctype, name, vals, per=16, static=False):
    cdata.append(f'{"static " if static else ""}const {ctype} {name}[{len(vals)}] = {{')
    for i in range(0, len(vals), per):
        cdata.append('    ' + ', '.join(str(v) for v in vals[i:i + per]) + ',')
    cdata.append('};')


def bank(b, a):
    return M[a] if a < 0x8000 else M[0x8000 + b * 0x4000 + a - 0x8000]


# ------------------------------------------------------------------ font (from build_assets)
font = (GEN / 'font_pens.bin').read_bytes()       # 1024 chars x 32 bytes, nibble = pen + 1
tlut = (GEN / 'txt_lut.bin').read_bytes()         # 64 colours x 256
tpal = (GEN / 'txt_pal.bin').read_bytes()         # per colour: 0 PAL2, 1 PAL3
fblank = (GEN / 'font_blank.bin').read_bytes()


def glyph(code, colour):
    """Arcade char (code 0-1023) in text colour 0-63 -> (32-byte Genesis tile, palette 0/1)."""
    raw = font[code * 32:code * 32 + 32]
    lut = tlut[colour * 256:colour * 256 + 256]
    return bytes(lut[b] for b in raw), tpal[colour]


def tile_px(t):
    a = np.zeros((8, 8), np.uint8)
    for y in range(8):
        for x in range(4):
            b = t[y * 4 + x]
            a[y, 2 * x] = b >> 4; a[y, 2 * x + 1] = b & 15
    return a


def px_tile(a):
    return bytes(((int(a[y, 2 * x]) & 15) << 4) | (int(a[y, 2 * x + 1]) & 15) for y in range(8) for x in range(4))


class TileSet:
    """Deduplicating tile store (with H/V flips)."""
    def __init__(self):
        self.tiles, self.index = [], {}

    def add(self, t):
        a = tile_px(t)
        for hf in (0, 1):
            for vf in (0, 1):
                b = a[:, ::-1] if hf else a
                b = b[::-1] if vf else b
                k = px_tile(b)
                if k in self.index:
                    return self.index[k], hf, vf
        self.index[t] = len(self.tiles); self.tiles.append(t)
        return len(self.tiles) - 1, 0, 0


# ------------------------------------------------------------------ $03BD text records
def text_record(a):
    """addr lo/hi, rows, cols, attr, chars ($FF n = n blanks). attr b0-5 colour, b6-7 code bits 8-9."""
    v = M[a] | M[a + 1] << 8
    rows, cols, attr = M[a + 2], M[a + 3], M[a + 4]
    codes, i = [], a + 5
    while len(codes) < rows * cols:
        if M[i] == 0xFF:
            codes += [0x27] * M[i + 1]; i += 2
        else:
            codes.append(M[i]); i += 1
    r, c = (v - 0xD000) // 64, (v - 0xD000) % 64
    return dict(row=r, col=c, rows=rows, cols=cols, attr=attr, codes=[c_ | ((attr >> 6) << 8) for c_ in codes])


REGION = chr(M[0x0AA0])   # $0B84: 'J' -> $0FA9, 'A' -> $10AC, 'N' -> $11C7
WARNING = {'J': 0x0FA9, 'A': 0x10AC, 'N': 0x11C7}[REGION]
# (name, ROM address). Genesis placement = arcade (col - 12, row - 2): the 320-px view is
# centred in the arcade's 384 px (text col c is at screen x (c-8)*8 - 32).
STRINGS = [('warning', WARNING), ('rank_head', 0x0DFC), ('rank_ord', 0x0E16),
           ('copyright', 0x0E41 if REGION == 'A' else 0x0E6C), ('push_start', 0x160B),
           ('one_player', 0x1621), ('one_or_two', 0x1633), ('bonus', 0x1646), ('credit', 0x165F),
           ('battle', 0x166D), ('oneup', 0x06C3), ('hi', 0x06CB), ('twoup', 0x06D2),
           ('naming', 0x1A16), ('continue', 0x1D4E), ('gameover', 0x1D6C),
           # "INSERT COIN" (attr 2): present in the World set's text records next to the logo
           # record, but never drawn by its code; the port's Arcade coin screen shows it
           ('insert_coin', 0x0E94)]
str_codes = []
cdata.append('const FeString fe_strings[FE_STRING_COUNT] = {')
hdr_enum = []
for name, a in STRINGS:
    r = text_record(a)
    codes = r['codes']
    # drop fully blank trailing/leading rows of the multi-row warning block
    off = len(str_codes)
    str_codes += codes
    row, col = r['row'] - 2, r['col'] - 12
    cdata.append(f"    {{{row}, {col}, {r['rows']}, {r['cols']}, {r['attr'] & 63}, {off}}},   /* ${a:04X} {name} */")
    hdr_enum.append(f'FE_STR_{name.upper()}')
cdata.append('};')
carr('u16', 'fe_string_codes', str_codes)
header.append('typedef struct { s8 row, col; u8 rows, cols, colour; u16 offset; } FeString;')
header.append('enum { ' + ', '.join(hdr_enum) + ', FE_STRING_COUNT };')
header.append('extern const FeString fe_strings[FE_STRING_COUNT];')
header.append('extern const u16 fe_string_codes[];')

# ------------------------------------------------------------------ logo ($0DF5 -> $0EA4)
logo = text_record(0x0EA4)
assert logo['rows'] == 8 and logo['cols'] == 32
lts = TileSet(); lmap = []
for c in logo['codes']:
    if fblank[c]:
        lmap.append(0); continue
    t, pal = glyph(c, logo['attr'] & 63)
    idx, hf, vf = lts.add(t)
    lmap.append((idx + 1) | (pal << 13) | (vf << 12) | (hf << 11))
emit('fe_logo_tiles', b''.join(lts.tiles), comment=f'{len(lts.tiles)} tiles ')
emit('fe_logo_map', be16(lmap), 'u16', '32x8: 0 blank, else (tile+1) | pal bit13 | flips ')
header.append(f'#define FE_LOGO_TILES {len(lts.tiles)}')
header.append(f"#define FE_LOGO_ROW {logo['row'] - 2}")
header.append(f"#define FE_LOGO_COL {logo['col'] - 12}")
print('logo:', len(lts.tiles), 'tiles')

# ------------------------------------------------------------------ "MD" under the logo (Home Screen)
# Not an arcade item: the letters M and D are cut out of the arcade logo's own art (the M of
# "ARMS", the D of "SIDE"): each letter = its white/cyan body (flood fill from seed pixels inside
# it) plus the logo's red outline pixels within 3 px of that body, so the strokes, outline and
# the white->cyan gradient are the logo's. Put side by side, centred under the logo.
lpx = np.zeros((64, 256), np.uint8)
for i, c in enumerate(logo['codes']):
    if not fblank[c]:
        r_, c_ = divmod(i, 32)
        lpx[r_ * 8:r_ * 8 + 8, c_ * 8:c_ * 8 + 8] = tile_px(glyph(c, logo['attr'] & 63)[0])
LOGO_PAL = glyph(logo['codes'][0], logo['attr'] & 63)[1]
RED = int(lpx[15, 100])                 # the outline pen (row 15: the red line over SIDE ARMS)
assert RED and lpx[20, 90] not in (0, RED)


def logo_letter(seeds, grow=3):
    body = np.zeros(lpx.shape, bool)
    stack = list(seeds)
    while stack:
        y, x = stack.pop()
        if not (0 <= y < 64 and 0 <= x < 256) or body[y, x] or lpx[y, x] in (0, RED):
            continue
        body[y, x] = True
        stack += [(y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)]
    near = body.copy()
    for _ in range(grow):
        n = near.copy()
        n[1:] |= near[:-1]; n[:-1] |= near[1:]; n[:, 1:] |= near[:, :-1]; n[:, :-1] |= near[:, 1:]
        near = n
    keep = body | (near & (lpx == RED))
    ys, xs = np.where(body)
    y0, y1 = ys.min() - 2, ys.max() + 3          # the logo's outline is 2 px above / below
    ys, xs = np.where(keep[y0:y1])
    return np.where(keep, lpx, 0)[y0:y1, xs.min():xs.max() + 1], y0


md_m, my0 = logo_letter([(20, 185), (20, 200), (40, 190)])     # M of "ARMS"
md_d, dy0 = logo_letter([(20, 90), (20, 100)])                 # D of "SIDE"
assert 20 < md_m.shape[1] < 40 and 20 < md_d.shape[1] < 40, (md_m.shape, md_d.shape)
top = min(my0, dy0)
h = max(my0 + md_m.shape[0], dy0 + md_d.shape[0]) - top
MD_COLS, MD_ROWS = 8, (h + 2 + 7) // 8
canvas = np.zeros((MD_ROWS * 8, MD_COLS * 8), np.uint8)
w = md_m.shape[1] + md_d.shape[1]
ox = (MD_COLS * 8 - w) // 2
for img, y0, x in ((md_m, my0, ox), (md_d, dy0, ox + md_m.shape[1])):
    sub = canvas[1 + y0 - top:1 + y0 - top + img.shape[0], x:x + img.shape[1]]
    sub[img > 0] = img[img > 0]
mts = TileSet(); mmap = []
for ty in range(MD_ROWS):
    for tx in range(MD_COLS):
        b = canvas[ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8]
        if not b.any():
            mmap.append(0); continue
        idx, hf, vf = mts.add(px_tile(b))
        mmap.append((idx + 1) | (LOGO_PAL << 13) | (vf << 12) | (hf << 11))
emit('fe_md_tiles', b''.join(mts.tiles), comment=f'{len(mts.tiles)} tiles ')
emit('fe_md_map', be16(mmap), 'u16', f'{MD_COLS}x{MD_ROWS}, same format as fe_logo_map ')
header.append(f'#define FE_MD_TILES {len(mts.tiles)}')
header.append(f'#define FE_MD_COLS {MD_COLS}')
header.append(f'#define FE_MD_ROWS {MD_ROWS}')
print('MD:', len(mts.tiles), 'tiles', MD_COLS, 'x', MD_ROWS)

# ------------------------------------------------------------------ weapon bar glyphs ($19BE, $1E7C)
BAR_COLOURS = [0x20, 0x25, 0x23, 0x24]     # none, owned, selected A, selected B
bar = bytearray(); barpal = []
for col in BAR_COLOURS:
    for code in range(0x50, 0x64):
        t, pal = glyph(code, col)
        bar += t
    barpal.append(pal)
emit('fe_bar_tiles', bytes(bar), comment='4 states x 20 glyphs ')
carr('u8', 'fe_bar_pal', barpal)
header.append('extern const u8 fe_bar_pal[4];')

# ------------------------------------------------------------------ background scenes
lo = M[0x14a37:0x14a37 + 0x400]; hi = M[0x14e37:0x14e37 + 0x400]
MD = []
for i in range(1024):
    r, g, b = palette_rgb(lo[i], hi[i])
    MD.append(to_md((r // 17, g // 17, b // 17)))
STAR = [MD[0x378 | k] for k in range(8)]          # same seeds as build_assets.py (stars)
seed0 = [STAR[1], STAR[3], STAR[5]]
seed1 = [STAR[6], STAR[7]]

bgt = decode_bgtiles(src.region('bgtiles'))
code, color, flags = bgmap_cells(src.region('bgmap'))

SCENES = [  # (name, set, arcade scroll x, y)
    ('title', 0, 0x180, 0x000),                    # $0C05: ranking screen city
    ('earth', 1, 0xB00, 0xE00), ('earth_flash', 1, 0xC80, 0xE00), ('earth_burnt', 1, 0xE00, 0xE00),  # $13E8-$1444
    ('burn0', 1, 0x9C0, 0x100), ('burn1', 1, 0xB40, 0x100), ('burn2', 1, 0xCC0, 0x100), ('burn3', 1, 0xE40, 0x100),
    ('burn4', 1, 0x9C0, 0x200), ('burn5', 1, 0xB40, 0x200), ('burn6', 1, 0xCC0, 0x200), ('burn7', 1, 0xE40, 0x200),
    ('burn8', 1, 0x480, 0x900), ('burn9', 1, 0x600, 0x900), ('burn10', 1, 0x480, 0xA00), ('burn11', 1, 0x600, 0xA00),
]


def world_view(sx, sy):
    """MD colour indices of the Genesis 320x224 view at arcade scroll (sx, sy): camera =
    scroll + (96, 16). Returns (H, W) array of colour tuples-ids and a transparency mask."""
    wx0, wy0 = sx + 96, sy + 16
    img = np.full((224, 320), -1, np.int32)
    for py in range(0, 224 + 32, 32):
        for px in range(0, 320 + 32, 32):
            wx, wy = (wx0 + px) & 0xFFF, (wy0 + py) & 0xFFF
            cx, cy = wx >> 5, wy >> 5
            t = bgt[code[cy, cx]]
            if flags[cy, cx] & 1: t = t[:, ::-1]
            if flags[cy, cx] & 2: t = t[::-1, :]
            ids = np.where(t == 15, -1, color[cy, cx] * 16 + t.astype(np.int32))
            ox, oy = px - (wx & 31), py - (wy & 31)
            x0, y0 = max(0, ox), max(0, oy)
            x1, y1 = min(320, ox + 32), min(224, oy + 32)
            if x1 > x0 and y1 > y0:
                img[y0:y1, x0:x1] = ids[y0 - oy:y1 - oy, x0 - ox:x1 - ox]
    return img


set_scenes = {}
for i, (name, s, x, y) in enumerate(SCENES):
    set_scenes.setdefault(s, []).append(i)
scene_maps = {}
set_info = []
for s, idxs in sorted(set_scenes.items()):
    views = {i: world_view(SCENES[i][2], SCENES[i][3]) for i in idxs}
    blocks, cells = [], []
    for i in idxs:
        v = views[i]
        for ty in range(28):
            for tx in range(40):
                b = v[ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8]
                hist = {}
                for cid, n in zip(*np.unique(b[b >= 0], return_counts=True)):
                    c = MD[int(cid)]; hist[c] = hist.get(c, 0) + int(n)
                blocks.append(hist); cells.append((i, tx, ty))
    pals, assign = fit(blocks, 2, 15, fixed=[seed0, seed1])
    ts = TileSet()
    maps = {i: [0] * (64 * 28) for i in idxs}
    lut = [{} for _ in range(2)]
    for (i, tx, ty), hist, p in zip(cells, blocks, assign):
        if not hist:
            continue
        p = int(p)
        b = views[i][ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8]
        px = np.zeros((8, 8), np.uint8)
        for yy in range(8):
            for xx in range(8):
                cid = int(b[yy, xx])
                if cid >= 0:
                    c = MD[cid]
                    if c not in lut[p]:
                        lut[p][c] = 1 + nearest(c, pals[p])
                    px[yy, xx] = lut[p][c]
        idx, hf, vf = ts.add(px_tile(px))
        maps[i][ty * 64 + tx] = 0x8000 | (p << 13) | (vf << 12) | (hf << 11) | (VRAM_BG_TILE + idx)
    assert len(ts.tiles) <= BG_CACHE_TILES, (s, len(ts.tiles))
    palwords = []
    for p in pals:
        palwords += [0] + [md_word(c) for c in p] + [0] * (15 - len(p))
    emit(f'fe_set{s}_tiles', b''.join(ts.tiles), comment=f'{len(ts.tiles)} tiles ')
    emit(f'fe_set{s}_pal', be16(palwords), 'u16', 'PAL0+PAL1 ')
    set_info.append((s, len(ts.tiles)))
    for i in idxs:
        scene_maps[i] = maps[i]
    print(f'scene set {s}: {len(idxs)} scenes, {len(ts.tiles)} tiles')
for i, (name, s, x, y) in enumerate(SCENES):
    emit(f'fe_scene{i}_map', be16(scene_maps[i]), 'u16', f'{name}: 64x28 plane B ')
header.append('typedef struct { const u8 *tiles; u16 count; const u16 *pal; } FeSceneSet;')
header.append('typedef struct { const u16 *map; u8 set; } FeScene;')
header.append(f'#define FE_SCENE_SETS {len(set_info)}')
header.append('extern const FeSceneSet fe_scene_sets[FE_SCENE_SETS];')
header.append('enum { ' + ', '.join(f'FE_SCENE_{n.upper()}' for n, *_ in SCENES) + ', FE_SCENE_COUNT };')
header.append('extern const FeScene fe_scenes[FE_SCENE_COUNT];')
cdata.append('const FeSceneSet fe_scene_sets[FE_SCENE_SETS] = {')
for s, n in set_info:
    cdata.append(f'    {{fe_set{s}_tiles, {n}, fe_set{s}_pal}},')
cdata.append('};')
cdata.append('const FeScene fe_scenes[FE_SCENE_COUNT] = {')
for i, (name, s, x, y) in enumerate(SCENES):
    cdata.append(f'    {{fe_scene{i}_map, {s}}},   /* {name}: arcade scroll ${x:03X},${y:03X} */')
cdata.append('};')

# ------------------------------------------------------------------ ranking, bonus tables


def bcd_points(b):
    return int(''.join(str(d) for d in b)) * 10   # 8 stored digits + a fixed '0'


rank = []
for i in range(5):
    e = M[0x0B34 + 16 * i:0x0B34 + 16 * i + 16]
    name = list(e[13:16])
    if i == 4:   # $0B04: region letter in the 5th name
        name[0] = {'J': 0x13, 'A': 0x0A, 'N': 0x17}.get(REGION, name[0])
    rank.append((bcd_points(e[:8]), name))
cdata.append('const FeRankEntry fe_default_ranking[5] = {')
for sc, nm in rank:
    cdata.append(f'    {{{sc}, {{{nm[0]}, {nm[1]}, {nm[2]}}}}},')
cdata.append('};')
header.append('typedef struct { u32 score; u8 name[3]; } FeRankEntry;   /* name = arcade char codes */')
header.append('extern const FeRankEntry fe_default_ranking[5];')

ext = []
for k in range(4):
    p = M[0x09EF + 2 * k] | M[0x09EF + 2 * k + 1] << 8
    vals, a = [], p
    while M[a:a + 8] != bytes([9] * 8):
        vals.append(bcd_points(M[a:a + 8])); a += 8
    ext.append(vals)
cdata.append('const u32 fe_extend_tables[4][6] = {   /* $09EF, 0-terminated */')
for v in ext:
    cdata.append('    {' + ', '.join(str(x) for x in v + [0] * (6 - len(v))) + '},')
cdata.append('};')
header.append('extern const u32 fe_extend_tables[4][6];')
lives = list(M[0x09ED:0x09EF])
header.append(f'#define FE_LIVES_A {lives[0]}   /* $09ED */')
header.append(f'#define FE_LIVES_B {lives[1]}')
diff = [v - 256 if v > 127 else v for v in M[0x8000 + 0x49:0x8000 + 0x49 + 8]]    # B0:$8049
carr('s8', 'fe_rank_offset', diff)
header.append('extern const s8 fe_rank_offset[8];   /* B0:$8049: rank $E017 = base + this[difficulty] */')
# B0:$80CA-$812F: each stage music ($21-$29, $36) also loads the enemy bullet speed level $E050
# from table $813C + 8 * stage, indexed by the difficulty (~DSW0 & 7)
carr('u8', 'fe_bullet_speed', list(M[0x813C:0x813C + 80]))
header.append('extern const u8 fe_bullet_speed[80];   /* B0:$813C: [stage music k * 8 + difficulty], k = $21.. -> 0.., $36 -> 9 */')

# ------------------------------------------------------------------ attract demo
DEMO_IN = [(0x9600, 0x9800), (0x9800, 0x9A00), (0x9A00, 0x9D00), (0x9D00, 0xA000)]
MAX_DEMO_FRAMES = 4000
for k, (a, end) in enumerate(DEMO_IN):
    # B2:$8032: the pointer starts at the table, duration 1 -> the first pair is at +2;
    # a duration byte of 0 lasts 256 frames.
    out, tot, p = [], 0, a + 2
    while p < end and tot < MAX_DEMO_FRAMES:
        v, n = bank(2, p), bank(2, p + 1) or 256
        out.append((v << 8) | (n & 0xFF)); tot += n; p += 2
    carr('u16', f'fe_demo_input{k}', out, static=True)
    cdata.append(f'#define FE_DEMO_INPUT{k}_LEN {len(out)}')
cdata.append('const FeDemoInput fe_demo_inputs[4] = {')
for k in range(4):
    cdata.append(f'    {{fe_demo_input{k}, FE_DEMO_INPUT{k}_LEN}},')
cdata.append('};')
header.append('typedef struct { const u16 *pairs; u16 count; } FeDemoInput;  /* value << 8 | frames (0 = 256) */')
header.append('extern const FeDemoInput fe_demo_inputs[4];   /* variant 0: P1, P2; variant 1: P1, P2 */')

# Demo scroll scripts, simulated like tools/extract_levels.py (1 px / 2 frames, records fire
# when the moving axis' low byte equals the trigger). Spawn records are mapped to the stage
# spawn table entry with the same command (tools/build_levels.py ordering) when one exists.
from extract_levels import Rom, decode_library, scan_script
rom = Rom(); lib = decode_library(rom)
spawn_ix = {}
try:
    lv = json.loads((GEN / 'levels.json').read_text()); sp = json.loads((GEN / 'spawns.json').read_text())
    for sn, (sec, st) in enumerate(zip(lv['sections'], sp['stages'])):
        ctrl = {c['ptr'] for c in sec['control']}
        n = 0
        for e in st['events']:
            if e['kind'] == 'resume_after_boss' or e['script'] in ctrl:
                continue
            key = (e.get('cmd', '').upper(), (e.get('routine') or
                   (e.get('objects') or [{}])[0].get('template', '')).upper())
            spawn_ix.setdefault(key, (sn, n))
            n += 1
except (OSError, KeyError, ValueError):
    pass


def simulate_demo(recs):
    """Scroll + script interpreter ($1FB7/$2044 as modelled by tools/extract_levels.py) from the
    demo start: scroll (0,0), X direction +1 ($0D6E-$0D7A). Yields (record, x, y) with the
    scroll position at which the record fires (before a teleport is applied)."""
    x = y = 0; lx, ly = 1, 0; i = 0; out = []
    while i < len(recs):
        y = (y + ly) & 0xFFF; x = (x + lx) & 0xFFF
        while i < len(recs):
            a, c, t, p = recs[i]
            cur = x if lx else y if ly else None
            if cur is None or (cur & 0xFF) != t:
                break
            i += 1
            if c == 0xFF:
                break
            out.append((recs[i - 1], x, y))
            info = lib.get(p, {}) if c == 0xFE else {}
            if info.get('op') == 'teleport':
                x, y = info['x'], info['y']
            elif info.get('op') == 'dir_x':
                lx = info['dir']
            elif info.get('op') == 'dir_y':
                ly = info['dir']
            elif c == 0xFE and p == 0x0BD1:
                return out
    return out


OPS = {'teleport': 0, 'dir_x': 1, 'dir_y': 2, 'music': 3, 'spawn': 4, 'end': 5}
for v, (start, stop) in enumerate(((0x8000, 0x8074), (0x8074, 0x815C))):
    recs = [r for r in scan_script(rom, start) if r[0] < stop]
    evs = []
    for (ptr, cmd, trig, tgt), x, y in simulate_demo(recs):
        info = lib.get(tgt, {}) if cmd == 0xFE else {}
        op, a, b, c = None, 0, 0, 0
        if info.get('op') == 'teleport':
            op, b, c = 'teleport', info['x'], info['y']
        elif info.get('op') in ('dir_x', 'dir_y'):
            d = info['dir']; op, a = info['op'], 0 if d == 0 else (1 if d == 1 else 2)
        elif cmd == 0xFE and tgt == 0x0BD1:
            op = 'end'                                   # B1:$806E: back to the title ($0BD1)
        elif cmd == 0xFE and tgt == 0x8130:
            op, a = 'music', 0x27                        # B0:$8130: sound $27 + bullet table
        elif info.get('op') in ('rank', 'music', 'halt', 'resume', 'pause', 'set_E048', 'boss'):
            continue
        else:
            sec, ix = spawn_ix.get((f'{cmd:02X}', f'{tgt:04X}'), (0xFF, 0xFFFF))
            op, a, b, c = 'spawn', cmd, tgt, ((sec << 12) | (ix & 0xFFF)) if sec != 0xFF else 0xFFFF
        evs.append(f"    {{{x}, {y}, {OPS[op]}, {a}, {b}, {c}}},   /* B1:${ptr:04X} {op} */")
    cdata.append(f'static const FeDemoEvent fe_demo_ev{v}[] = {{')
    cdata += evs
    cdata.append('};')
cdata.append('const FeDemoScript fe_demo_scripts[2] = {')
for v in range(2):
    cdata.append(f'    {{fe_demo_ev{v}, sizeof(fe_demo_ev{v}) / sizeof(FeDemoEvent)}},')
cdata.append('};')
header.append('enum { FE_DEV_TELEPORT, FE_DEV_DIR_X, FE_DEV_DIR_Y, FE_DEV_MUSIC, FE_DEV_SPAWN, FE_DEV_END };')
header.append('/* x, y: scroll at which the record fires. TELEPORT b,c = x,y; DIR a = 0 stop, 1 +, 2 -;')
header.append(' * MUSIC a = sound; SPAWN a = script command, b = arcade target (routine/template),')
header.append(' * c = matching stage spawn (section << 12 | index) or $FFFF */')
header.append('typedef struct { u16 x, y; u8 op, a; u16 b, c; } FeDemoEvent;')
header.append('typedef struct { const FeDemoEvent *ev; u16 count; } FeDemoScript;')
header.append('extern const FeDemoScript fe_demo_scripts[2];')

# ------------------------------------------------------------------ outputs
lines = ['/* Generated by tools/build_frontend.py. */', '.section .rodata', '.align 2']
for name in symbols:
    # 512-byte aligned: DMA sources must not straddle a 128 KB boundary (hud.c streams fe_bar_tiles
    # in 128-byte runs with DMA_queueDmaFast)
    lines += [f'.global {name}', '.balign 512', f'{name}:', f'.incbin "res/generated/{name}.bin"']
(SRC / 'frontend.s').write_text('\n'.join(lines) + '\n')
(SRC / 'frontend_data.c').write_text('\n'.join(cdata) + '\n')
(INC / 'frontend.h').write_text('\n'.join(header) + '\n')
print('frontend:', len(symbols), 'blobs, region', REGION)
