#!/usr/bin/env python3
"""Boss data for the native boss module (src/boss*.c), converted from the arcade ROM at build time.

Run by tools/build_assets.py after the sprite tables (sprite_lut.bin, sprite_pens.bin) and the
zone palettes (zoneN_pal.bin) have been written. Outputs (ignored by VCS):
  src/gen/boss_data.c, inc/gen/boss_data.h

What is converted (docs/re/objects.md section 6.1, docs/re/levels.md section 2, docs/bosses.md):
  * a pattern bank of every 32x32 block the boss objects show (sprite boss bodies $69D0/$6C12/$6DB4
    in each colour they use, wheel pods/core, final boss segments, explosions) and of the 16x16
    projectile patterns, pre-converted to Genesis tiles; the boss module DMAs them into VRAM
    blocks lent by the BG metatile cache;
  * weapon tables: laser-burst intervals ($35C3/$35D3/$35E3) and beam layout ($35F3), homing
    missile intervals ($376D/$377D/$378D), missile heading steps ($4BA9) and launch steps;
  * death explosion schedules ($397C, $3A6C) and the 2x2 explosion animation ($3B16);
  * the aim sector table ($0780), enemy-bullet step cycles per speed level ($4022/$4066/$40AA/$40EE),
    score table ($2337);
  * BG wheel bosses: the three wheel copies of each wheel ($70D2/$70E2/$70F2) turned into
    background frame maps relative to the halt zone (+ extra metatiles quantized to that zone's
    palettes), the 24-point orbit of the wheel pods ($7102) and pod start table ($720C);
  * final boss $5FC3: per-heading motion steps for head / hurt head / body / tail
    ($6312/$62F2/$6332/$6352), start timers and the explosion steps;
  * ending texts ($3BC9 "CONGRATURATIONS", $3BF9 staff roll).
"""
import json, struct, sys
from pathlib import Path
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import Source, ROOT, decode_bgtiles, bgmap_cells, palette_rgb
from quantize import to_md, nearest
import zones as zonecfg
import parallax_split

GEN = ROOT / 'res/generated'; SRC = ROOT / 'src/gen'; INC = ROOT / 'inc/gen'
src = Source()
M = src.region('maincpu')


def w16(a):
    return M[a] | M[a + 1] << 8


def s8(v):
    return v - 256 if v > 127 else v


def steps(a, limit=64):
    """Follow a motion script from the step at a: [(frames, code, colour, dy, dx)], end op."""
    out = []; seen = set()
    while len(out) < limit:
        if a in seen:
            return out, ('loop', a)
        seen.add(a)
        d = M[a]
        if d == 0:
            return out, ('native', M[a + 1] | M[a + 2] << 8)
        if d == 0xFF:
            a = w16(a + 1); continue
        if d == 0xFE:
            return out, ('kill', 0)
        out.append((d, M[a + 1] | ((M[a + 2] >> 5) << 8), M[a + 2] & 15, s8(M[a + 3]), s8(M[a + 4])))
        a += 5
    raise ValueError(hex(a))


c = ['/* Generated by tools/build_bosses.py from the original ROM set. Do not edit. */',
     '#include "gen/boss_data.h"', '']
h = ['/* Generated by tools/build_bosses.py. Do not edit. */', '#pragma once', '#include <genesis.h>',
     '#include "bg.h"', '',
     'typedef struct { u8 frames, colour; u16 code; s8 dy, dx; } BossStep;   /* one motion step */']


def arr(ctype, name, vals, per=16, comment=''):
    h.append(f'extern const {ctype} {name}[{len(vals)}];{"  /* " + comment + " */" if comment else ""}')
    c.append(f'const {ctype} {name}[{len(vals)}] = {{')
    for i in range(0, len(vals), per):
        c.append('    ' + ', '.join(str(v) for v in vals[i:i + per]) + ',')
    c.append('};')


def step_init(s):
    f, code, col, dy, dx = s
    return f'{{{f}, {col}, 0x{code:03X}, {dy}, {dx}}}'


def steps_arr(name, ss, comment=''):
    h.append(f'extern const BossStep {name}[{len(ss)}];{"  /* " + comment + " */" if comment else ""}')
    c.append(f'const BossStep {name}[{len(ss)}] = {{ ' + ', '.join(step_init(s) for s in ss) + ' };')


# ------------------------------------------------------------------ shared tables
arr('u8', 'aim_sector', list(M[0x0780:0x07C0]), comment='$0780: 8 octant rows x (5 ratio sectors + pad) -> direction 0-31')
score = []
for idx in range(0, 0x80, 8):
    # $2272: 8 unpacked BCD digits ending (units) at $2337+idx, read downwards; displayed x10
    score.append(sum(M[0x2337 + idx - k] * 10 ** k for k in range(8) if idx - k >= 0) * 10)
arr('u32', 'score_points', score, comment='$2337 indexed by score index / 8 (points)')

# enemy bullet $4000: per speed level, per direction, the per-frame (dy,dx) cycle (always 4 frames)
bvel = []
for lv, tab in enumerate((0x4022, 0x4066, 0x40AA, 0x40EE)):
    for d in range(32):
        a = w16(tab + 2 * d) + 5
        seq = []
        ss, end = steps(a)
        # play the script for 12 frames (loops are 2- or 4-step cycles of 1-frame steps)
        i = 0; cur = ss; ptr = a
        frames = []
        while len(frames) < 12:
            st, en = steps(ptr)
            for s in st:
                frames += [(s[3], s[4])] * s[0]
            assert en[0] == 'loop', (hex(tab), d, en)
            ptr = en[1]
        frames = frames[:12]
        assert frames[0:4] == frames[4:8] == frames[8:12], (lv, d, frames)
        for dy, dx in frames[:4]:
            bvel += [dy, dx]
arr('s8', 'bullet_cycle', bvel, per=8, comment='[speed level 3..6][dir 0..31][4 frames][dy,dx] ($4022/$4066/$40AA/$40EE)')

# ------------------------------------------------------------------ sprite bosses
lut = (GEN / 'sprite_lut.bin').read_bytes()
pens = (GEN / 'sprite_pens.bin').read_bytes()


def conv(code, col):
    l = lut[col * 16:col * 16 + 16]
    return bytes((l[b >> 4] << 4) | l[b & 15] for b in pens[code * 128:code * 128 + 128])


def block32(code, col):
    """2x2 cells c, c+1, c+8, c+9 as one 4x4-tile sprite (column-major)."""
    a, b, cc, d = conv(code, col), conv(code + 1, col), conv(code + 8, col), conv(code + 9, col)
    return a[:64] + cc[:64] + a[64:] + cc[64:] + b[:64] + d[:64] + b[64:] + d[64:]


BOSSES = [(0x4A0, (14, 8)), (0x4C0, (14, 8)), (0x4E0, (5, 0, 8))]   # $69F7/$6C39/$6DDB codes, colours shown
h.append('#define BOSS_BODY_COLOURS 3')
h.append('extern const u8 boss_body_colours[3][3];   /* colours each sprite boss shows besides 15 (= hidden) */')
c.append('const u8 boss_body_colours[3][3] = { ' + ', '.join('{' + ', '.join(str(x) for x in (list(cols) + [255] * 3)[:3]) + '}' for _, cols in BOSSES) + ' };')
blocks = set()        # (code, colour) of every 2x2 pattern the boss objects show; banked at the end
for base, cols in BOSSES:
    for col in cols:
        for k in range(8):
            blocks.add((base + 16 * (k // 4) + 2 * (k % 4), col))


# laser burst task $3522/$3527/$352C: wait table (x6 frames) and beam layout $35F3
arr('u8', 'laser_wait', list(M[0x35C3:0x35F3]), comment='3 bosses x 16, in units of 6 frames ($35C3/$35D3/$35E3)')
beams = []
for i in range(8):
    mot, srcrec = w16(0x35F3 + 4 * i), w16(0x35F5 + 4 * i)
    (f, code, col, dy, dx), = steps(mot + 5)[0][:1]
    r = (srcrec - 0xFB00) // 32
    beams.append((code, col, dy, dx, r // 8, r % 8, f))
h.append('typedef struct { u16 code; u8 colour; s8 dy, dx; u8 row, col, frames; } BossBeam;')
h.append('extern const BossBeam laser_beams[8];  /* $35F3: step + source cell of the 8 beam records */')
c.append('const BossBeam laser_beams[8] = { ' + ', '.join(f'{{0x{b[0]:03X}, {b[1]}, {b[2]}, {b[3]}, {b[4]}, {b[5]}, {b[6]}}}' for b in beams) + ' };')
arr('u8', 'missile_wait', list(M[0x376D:0x379D]), comment='3 bosses x 16, units of 6 frames ($376D/$377D/$378D)')
mh = []
for hd in range(16):
    ss, en = steps(w16(0x4BA9 + 2 * hd))
    assert len(ss) == 1 and en == ('native', 0x4B50), (hd, ss, en)
    mh.append(ss[0])
steps_arr('missile_heading', mh, '$4BA9: homing missile $4B89, one 7-frame step per heading/2')
for name, ptr in (('missile_launch_down', 0x4BCC), ('missile_launch_up', 0x4BE1), ('missile_launch_left', 0x4BD4)):
    ss, en = steps(ptr + 5)
    assert en == ('native', 0x4B50), (name, en)
    steps_arr(name, ss, f'${ptr:04X}: launch steps before homing')

for name, a in (('blasts_sprite', 0x397C), ('blasts_wheel', 0x3A6C)):
    a0 = a; v = []
    while M[a + 2] != 0xFF:
        v += [s8(M[a]), s8(M[a + 1]), M[a + 2]]; a += 3
    arr('s8', name, v, per=12, comment=f'${a0:04X}: (dy, dx/2, frames to next) explosion offsets from the boss centre')
ss, en = steps(0x3B11 + 5)
steps_arr('explosion_steps', ss, '$3B16: 2x2 explosion (template $3AF6)')
ss, en = steps(0x4DAB)
steps_arr('small_explosion_steps', ss, '$4DAB: 1x1 explosion (missiles)')

# ------------------------------------------------------------------ wheel bosses
code_m, color_m, flags_m = bgmap_cells(src.region('bgmap'))
bgt = decode_bgtiles(src.region('bgtiles'))
main = M
lo = main[0x14a37:0x14a37 + 0x400]; hi = main[0x14e37:0x14e37 + 0x400]
MD = [to_md(tuple(x // 17 for x in palette_rgb(lo[i], hi[i]))) for i in range(1024)]
lv = json.loads((GEN / 'levels.json').read_text())
ZONES = zonecfg.ZONES


def zone_has(zi, cx, cy):
    x0, y0, w, hh = ZONES[zi]['rect']
    return x0 <= cx < x0 + w and y0 <= cy < y0 + hh


def auto_zone(cur, sx, sy):
    """bg.c auto_zone(): keep the current zone while it holds the view centre, else first match."""
    cx, cy = (sx + 96 + 160) >> 5, (sy + 16 + 112) >> 5
    if cur is not None and zone_has(cur, cx, cy):
        return cur
    for i in range(len(ZONES)):
        if zone_has(i, cx, cy):
            return i
    return cur


# zone in use at each scroll position along the game path (sections in order)
zone_at_halt = {}
cur = None
for s in lv['sections']:
    for leg in s['legs']:
        (x0, y0), (x1, y1) = leg['start'], leg['end']
        n = max(abs(x1 - x0), abs(y1 - y0), 1)
        for t in range(0, n + 1, 2):
            cur = auto_zone(cur, x0 + (x1 - x0) * t // n, y0 + (y1 - y0) * t // n)
        zone_at_halt[(s['section'], x1, y1)] = cur

WHEELS = []
for wi, tab in enumerate((0x70D2, 0x70E2, 0x70F2)):
    ent = [(w16(tab + 4 * k + 2), w16(tab + 4 * k)) for k in range(4)]   # (X, Y) scroll
    WHEELS.append(ent)
WHEEL_SECTION = [2, 4, 9]
h.append('/* BG wheel bosses: scroll copies (arcade $70D2/$70E2/$70F2); copy 3 = next section start */')
h.append('typedef struct { u16 copy_x[4], copy_y[4]; const BgFrames *frames, *frames_home; } WheelInfo;   /* frames_home: Home, sockets filled (docs/parallax.md) */')
h.append('extern const WheelInfo wheel_info[3];')
winfo = []
for wi, ent in enumerate(WHEELS):
    sec = WHEEL_SECTION[wi]
    halt = [k for k in zone_at_halt if k[0] == sec and abs(k[1] - ent[0][0]) <= 4 and k[2] == ent[0][1]]
    assert halt, (wi, ent)
    zi = zone_at_halt[halt[0]]
    x0, y0, zw, zh = ZONES[zi]['rect']
    metas = sorted(set((code_m[r, cc], color_m[r, cc]) for r in range(y0, y0 + zh) for cc in range(x0, x0 + zw)))
    mid = {(int(a), int(b)): i for i, (a, b) in enumerate(metas)}
    pal_words = struct.unpack('>32H', (GEN / f'zone{zi}_pal.bin').read_bytes())
    pals = [[((wd >> 1) & 7, (wd >> 5) & 7, (wd >> 9) & 7) for wd in pal_words[p * 16 + 1:p * 16 + 16]] for p in range(2)]
    cx0, cy0 = (ent[0][0] + 96) >> 5, (ent[0][1] + 16) >> 5
    W, H = 11, 8

    def frames(tag, fills):
        """the 3 frames as a BgFrames; fills (Home): {code: mask} of the filled wheel sockets
        (tools/parallax_split.py); a changed metatile becomes an extra one"""
        extra = []; emap = {}
        maps = []
        for k in range(3):
            bx, by = (ent[k][0] + 96) >> 5, (ent[k][1] + 16) >> 5
            for j in range(H):
                for i in range(W):
                    cx, cy = (bx + i) & 127, (by + j) & 127
                    cd, cl = int(code_m[cy, cx]), int(color_m[cy, cx])
                    fl = int(flags_m[cy, cx])
                    t = bgt[cd]
                    if cd in fills:
                        t = t.copy()
                        t[fills[cd]] = min(range(15), key=lambda pen: sum(MD[cl * 16 + pen]))
                    elif (cd, cl) in mid:
                        maps.append(mid[(cd, cl)] | ((fl & 1) << 14) | ((fl & 2) << 14))
                        continue
                    key = (cd, cl, t.tobytes())
                    if key not in emap:
                        emap[key] = len(metas) + len(extra); extra.append((cl, t))
                    maps.append(emap[key] | ((fl & 1) << 14) | ((fl & 2) << 14))
        tiles = bytearray(); tmpl = []
        for (cl, t) in extra:
            for sy in range(4):
                for sx in range(4):
                    sub = t[sy * 8:sy * 8 + 8, sx * 8:sx * 8 + 8]
                    errs = []
                    for p in range(2):
                        e = 0
                        for pen in np.unique(sub):
                            if pen == 15: continue
                            col = np.array(MD[cl * 16 + int(pen)], float); pc = np.array(pals[p], float)
                            e += ((pc - col) ** 2).sum(1).min() * int((sub == pen).sum())
                        errs.append(e)
                    p = int(np.argmin(errs))
                    lk = {pen: (0 if pen == 15 else 1 + nearest(MD[cl * 16 + pen], pals[p])) for pen in range(16)}
                    px = np.vectorize(lk.get)(sub)
                    for row in px:
                        for x in range(0, 8, 2):
                            tiles.append((int(row[x]) << 4) | int(row[x + 1]))
                    tmpl.append(0 if not px.any() else (0x8000 | (p << 13) | (sy * 4 + sx)))
        n = len(extra)
        c.append(f'static const u16 wheel{tag}_maps[{len(maps)}] = {{')
        for j in range(0, len(maps), W):
            c.append('    ' + ', '.join(f'0x{v:04X}' for v in maps[j:j + W]) + ',')
        c.append('};')
        if n:
            c.append(f'static const u8 wheel{tag}_tiles[{len(tiles)}] __attribute__((aligned(512))) = {{')
            for j in range(0, len(tiles), 32):
                c.append('    ' + ','.join(f'0x{x:02X}' for x in tiles[j:j + 32]) + ',')
            c.append('};')
            c.append(f'static const u16 wheel{tag}_tmpl[{len(tmpl)}] = {{ ' + ', '.join(f'0x{v:04X}' for v in tmpl) + ' };')
        c.append(f'static const BgFrames wheel{tag}_frames = {{ {zi}, {cx0}, {cy0}, {W}, {H}, 3, wheel{tag}_maps, {n}, '
                 f'{"wheel%s_tiles" % tag if n else "NULL"}, {"wheel%s_tmpl" % tag if n else "NULL"} }};')
        print(f'wheel {wi + 1}{" (Home)" if fills else ""}: zone {zi} ({ZONES[zi]["name"]}), '
              f'{len(set(m & 0xFFF for m in maps))} metatiles, {n} extra')
        return f'&wheel{tag}_frames'

    plain = frames(str(wi), {})
    fills = parallax_split.wheel_fill()
    used = {int(code_m[((e[1] + 16) >> 5) + j & 127, ((e[0] + 96) >> 5) + i & 127])
            for e in ent[:3] for i in range(W) for j in range(H)}
    home = frames(f'{wi}h', fills) if used & set(fills) else 'NULL'
    winfo.append(f'    {{ {{{", ".join(str(e[0]) for e in ent)}}}, {{{", ".join(str(e[1]) for e in ent)}}}, {plain}, {home} }},')
c.append('const WheelInfo wheel_info[3] = {'); c += winfo; c.append('};')

orbit = []
for k in range(24):
    a = 0x7102 + 3 * k
    orbit += [M[a + 1], M[a + 2] | ((M[a] & 0x10) << 4)]
arr('u16', 'wheel_orbit', orbit, comment='$7102: 24 pod positions (raw y, raw x) around the wheel')
pods = []
for k in range(8):
    pods += [M[0x720C + 2 * k], M[0x720D + 2 * k]]
arr('u8', 'wheel_pod_start', pods, comment='$720C: per pod (raw y, delay frames) - template $721C at x $1BF')
for name, a in (('pod_fire_steps', 0x73C1), ('pod_idle_steps', 0x73D5), ('core_idle_steps', 0x742A), ('core_hit_steps', 0x74A1)):
    ss, en = steps(a)
    steps_arr(name, ss, f'${a:04X}')
ss, en = steps(0x7353)
steps_arr('pod_beam_steps', ss, '$7353: wheel #2 pod beam (template $7333), 2 records')

# ------------------------------------------------------------------ final boss $5FC3
fsteps = []; fidx = []
for tab in (0x6312, 0x62F2, 0x6332, 0x6352):
    for hd in range(16):
        ss, en = steps(w16(tab + 2 * hd))
        assert en == ('native', 0x60AB), (hex(tab), hd, en)
        fidx += [len(fsteps), len(ss)]
        fsteps += ss
steps_arr('final_steps', fsteps, 'final boss motion steps')
arr('u16', 'final_motion', fidx, comment='[head $6312, hurt head $62F2, body $6332, tail $6352][heading/2] = (first step, count)')
ss, en = steps(0x66A5 + 5)
steps_arr('final_entry_steps', ss, '$66AA: entry step (template $6372)')
for name, a in (('final_blast_steps', 0x69AC),):
    ss, en = steps(a)
    steps_arr(name, ss, f'${a:04X}: segment explosion')
arr('u8', 'final_start', [M[0x5FDE + 5 * k] for k in range(8)], comment='$5FDD: segment start timers')
tm = M[0x6372:0x6392]
h.append(f'#define FINAL_HP {tm[11]}            /* $6372 +B */')
h.append(f'#define FINAL_HEAD_HP {M[0x6024]}         /* $6023 */')
h.append(f'#define FINAL_SCORE_IDX {tm[0x15]}       /* $6372 +15 */')
h.append(f'#define FINAL_LAST_SCORE_IDX {M[0x6029]}  /* $6028: segment 5 */')

# ------------------------------------------------------------------ ending texts
CH = {0x27: ' ', 0x28: '.', 0x2C: ',', 0x40: ' ', 0x47: '&', 0x2B: '.'}


def text(off):
    a = M[off] | M[off + 1] << 8; rows, cols = M[off + 2], M[off + 3]; p = off + 5; out = []
    for r in range(rows):
        s = ''; run = 0
        for _ in range(cols):
            if run:
                run -= 1; s += ' '; continue
            v = M[p]
            if v == 0xFF:
                run = M[p + 1] - 1; p += 2; s += ' '; continue
            s += chr(48 + v) if v < 10 else chr(55 + v) if v < 36 else CH.get(v, ' '); p += 1
        out.append(s.rstrip())
    return (a - 0xD000) % 64, (a - 0xD000) // 64, out


for name, off in (('ending_congrats', 0x3BC9), ('ending_staff', 0x3BF9)):
    col, row, lines = text(off)
    h.append(f'#define {name.upper()}_COL {col}   /* arcade text column (of 64; 48 visible from 8) */')
    h.append(f'#define {name.upper()}_ROW {row}')
    h.append(f'#define {name.upper()}_LINES {len(lines)}')
    h.append(f'extern const char *const {name}[{len(lines)}];')
    c.append(f'const char *const {name}[{len(lines)}] = {{ ' + ', '.join(json.dumps(l) for l in lines) + ' };')

# ------------------------------------------------------------------ 2x2 pattern bank
# every 32x32 pattern of the boss objects (sprite boss bodies, wheel pods/core, final boss
# segments, explosions), pre-converted so the boss module can DMA them into VRAM blocks
# lent by the BG cache (src/boss.c, bc_draw)
for a in (0x3B16, 0x69AC, 0x73C1, 0x742A, 0x74A1):
    for f_, code, col, dy, dx in steps(a)[0]:
        if code and col != 15: blocks.add((code, col))
blocks.add((0x430, 5))                                   # $7264
for f_, code, col, dy, dx in fsteps:
    blocks.add((code, col))
blocks.add((0x670, 3))                                   # $66AA
keys = sorted(code | (col << 11) for code, col in blocks)
h.append(f'#define BOSS_BLOCKS {len(keys)}')
h.append('extern const u16 boss_block_keys[BOSS_BLOCKS];   /* sorted code | colour << 11 */')
h.append('extern const u8 boss_block_data[];               /* BOSS_BLOCKS x 512 bytes, 4x4-tile sprites */')
arr_c = []
c.append(f'const u16 boss_block_keys[BOSS_BLOCKS] = {{ ' + ', '.join(f'0x{k:04X}' for k in keys) + ' };')
c.append(f'const u8 boss_block_data[{len(keys) * 512}] __attribute__((aligned(512))) = {{')
for k in keys:
    d = block32(k & 0x7FF, k >> 11)
    for j in range(0, 512, 32):
        c.append('    ' + ','.join(f'0x{x:02X}' for x in d[j:j + 32]) + ',')
c.append('};')
print('boss pattern bank:', len(keys), 'blocks', len(keys) // 2, 'KB')
# 16x16 patterns of the boss projectiles (beams $3613/$7333, homing missiles $4B89, bullets $4000,
# 1x1 explosion $4DAB), kept in quarter blocks by the boss module
small = set()
for b_ in beams:
    small.add((b_[0], b_[1]))
for st in (mh,):
    for f_, code, col, dy, dx in st:
        small.add((code, col))
for a_ in (0x4BD1, 0x4BE6, 0x4BD9, 0x7353, 0x4DAB):
    for f_, code, col, dy, dx in steps(a_)[0]:
        small.add((code, col))
small |= {(0x126, 8), (0x127, 7)}
skeys = sorted(code | (col << 11) for code, col in small)
h.append(f'#define BOSS_SMALL {len(skeys)}')
h.append('extern const u16 boss_small_keys[BOSS_SMALL];    /* sorted code | colour << 11 */')
h.append('extern const u8 boss_small_data[];                /* BOSS_SMALL x 128 bytes, 2x2-tile sprites */')
c.append('const u16 boss_small_keys[BOSS_SMALL] = { ' + ', '.join(f'0x{k:04X}' for k in skeys) + ' };')
c.append(f'const u8 boss_small_data[{len(skeys) * 128}] __attribute__((aligned(128))) = {{')
for k in skeys:
    d = conv(k & 0x7FF, k >> 11)
    for j in range(0, 128, 32):
        c.append('    ' + ','.join(f'0x{x:02X}' for x in d[j:j + 32]) + ',')
c.append('};')
print('boss small bank:', len(skeys), 'patterns')

(SRC / 'boss_data.c').write_text('\n'.join(c) + '\n')
(INC / 'boss_data.h').write_text('\n'.join(h) + '\n')
print('bosses:', len(fsteps), 'final steps')
