#!/usr/bin/env python3
"""Extract player / game-flow tables from the Side Arms main CPU ROM -> res/generated/player.json.

All addresses are documented in docs/re/flow_player.md. Bank n lives at region offset 0x8000+n*0x4000
and is cited as B<n>:$xxxx (CPU address $8000-$BFFF). Fixed ROM ($0000-$7FFF) is cited as $xxxx.
"""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from arcade_source import Source, ROOT

M = Source().region('maincpu')


def fx(a, n=1):
    return M[a:a + n]


def bk(bank, a, n=1):
    o = 0x8000 + bank * 0x4000 + (a - 0x8000)
    return M[o:o + n]


def s8(v):
    return v - 256 if v > 127 else v


def text_char(c):
    if c < 10: return str(c)
    if c < 0x24: return chr(ord('A') + c - 10)
    if c == 0x27: return ' '
    if c == 0x2b: return '.'
    return '{%02X}' % c


def text_string(a):
    """$03BD format: addr lo, addr hi, rows, cols, attr, chars (FF n = n blanks)."""
    b = fx(a, 64)
    vaddr = b[0] | b[1] << 8
    rows, cols, attr = b[2], b[3], b[4]
    out, codes, i = [], [], 5
    while len(codes) < rows * cols:
        if b[i] == 0xFF:
            codes += [0x27] * b[i + 1]; i += 2
        else:
            codes.append(b[i]); i += 1
    row, col = (vaddr - 0xD000) // 64, (vaddr - 0xD000) % 64
    return dict(rom=f'${a:04X}', vram=f'${vaddr:04X}', row=row, col=col, screen_x=(col - 8) * 8, screen_y=(row - 2) * 8,
                rows=rows, cols=cols, attr=attr, codes=[f'{c:02X}' for c in codes],
                text=''.join(text_char(c) for c in codes))


def move_table(bank, a):
    """16 entries indexed by joystick nibble (b0 R, b1 L, b2 D, b3 U); each (dy, dx)."""
    raw = bk(bank, a, 32)
    names = {1: 'R', 2: 'L', 4: 'D', 5: 'DR', 6: 'DL', 8: 'U', 9: 'UR', 10: 'UL'}
    return {names.get(i, f'idx{i}'): [s8(raw[2 * i]), s8(raw[2 * i + 1])] for i in range(16) if i in names}


def shot_rec(a):
    r = bk(2, a, 8)
    return dict(rom=f'B2:${a:04X}', code=r[0], attr=r[1], color=r[1] & 15, code_hi=(r[1] >> 5) & 7,
                dy=s8(r[2]), dx=s8(r[3]), vy=s8(r[4]), vx=s8(r[5]), hit_half_h=r[6], hit_half_w=r[7])


def shots(a, n):
    return [shot_rec(a + 8 * i) for i in range(n)]


def bcd8(b):
    return int(''.join(str(d) for d in b)) * 10   # displayed value = 8 stored digits followed by a fixed '0'


out = {}
out['_doc'] = 'Generated by tools/extract_player.py from the original ROM; see docs/re/flow_player.md'

out['movement'] = {
    'speed1': dict(rom='B2:$864C', **move_table(2, 0x864C)),
    'speed2': dict(rom='B2:$866C', **move_table(2, 0x866C)),
    'speed3': dict(rom='B2:$868C', **move_table(2, 0x868C)),
    'combined_robot': dict(rom='B2:$86AC', **move_table(2, 0x86AC)),
    'bounds': dict(y_min=0x20, y_max=0xC0, x_min=0x50, x_max=0x190, cite='B2:$83A1-$83EA (x is 9-bit: attr bit4 = x bit8)'),
}

out['shots'] = {
    'normal_left_right': shots(0x90DF, 2),
    'bit_shot_left_right': shots(0x90EF, 2),
    'bit_mode_normal_left_right': shots(0x90FF, 2),
    'sg_l1_left': shots(0x910F, 3), 'sg_l1_right': shots(0x9127, 3),
    'sg_l2_left': shots(0x913F, 5), 'sg_l2_right': shots(0x9167, 5),
    'sg_l3_left': shots(0x918F, 7), 'sg_l3_right': shots(0x91C7, 7),
    'mbl_left_right': shots(0x91FF, 2),
    '3way_left': shots(0x920F, 3), '3way_right': shots(0x9227, 3),
    'auto10_left_right': shots(0x923F, 2),
    'auto11_left': shots(0x924F, 3), 'auto11_right': shots(0x9267, 3),
    'combined_a': shots(0x927F, 8), 'combined_b': shots(0x92BF, 8),
}

# BIT orbit path: (dy, dx, code) triples relative to (player y, player x+16), $80 terminates -> restart at $1F56
path, a = [], 0x1F56
while M[a] != 0x80:
    path.append([s8(M[a]), s8(M[a + 1]), M[a + 2]]); a += 3
out['bit_orbit'] = dict(rom='$1F56', steps=path, start_index={'bit1': 0, 'bit2_level2': (0x1F86 - 0x1F56) // 3,
                       'bit2_level3': (0x1F74 - 0x1F56) // 3, 'bit3_level3': (0x1F98 - 0x1F56) // 3})

anim, a = [], 0x23AD + 3
while M[a + 2]:
    anim.append(dict(code=M[a] | ((M[a + 1] >> 5) & 7) << 8, attr=M[a + 1], frames=M[a + 2])); a += 3
out['death_anim'] = dict(rom='$23AD', note='4-sprite composite: code, code+1, code+8, code+9', frames=anim)


def desc(a):
    b = fx(a, 0x2A)
    w = lambda o: f'${b[o] | b[o + 1] << 8:04X}'
    return dict(rom=f'${a:04X}', start_mask=b[0], player_bit=b[1], base_code=b[3], attr_H=b[4], attr_V=b[5],
                spawn_H=dict(y=b[6], x=b[8]), spawn_V=dict(y=b[7], x=b[9]), str_bar1=w(0x0A), str_bar2=w(0x0C),
                continue_digit=w(0x0E), name_vram=w(0x12), score=w(0x14), str_continue=w(0x16), str_gameover=w(0x18),
                extend_ptr_var=w(0x1A), naming_timer_var=w(0x1C), str_naming=w(0x1E), naming_vram=w(0x20),
                input_port=w(0x22), name_store=w(0x24), naming_debounce=w(0x26), naming_index=w(0x28))


out['player_descriptors'] = {'P1': desc(0x1CFA), 'P2': desc(0x1D24)}

ext = {}
for i, p in enumerate((0x09F7, 0x0A07, 0x0A37, 0x0A5F)):
    vals, a = [], p
    while fx(a, 8) != bytes([9] * 8):
        vals.append(bcd8(fx(a, 8))); a += 8
    ext[f'dsw_index{i}'] = dict(rom=f'${p:04X}', scores=vals)
out['extend_tables'] = dict(selector='(~DSW0 & 0x30) >> 3 -> pointer table $09EF', **ext)
out['lives_by_dsw'] = dict(rom='$09ED', values=list(fx(0x09ED, 2)), selector='(~DSW0 >> 3) & 1')
out['coin_table'] = dict(rom='$0A7F', note='(credits awarded, coins required) indexed by inverted DSW1 coin field',
                         entries=[list(fx(0x0A7F + 2 * i, 2)) for i in range(8)])

rank = []
for i in range(5):
    e = fx(0x0B34 + 16 * i, 16)
    rank.append(dict(score=bcd8(e[:8]), name=''.join(text_char(c) for c in e[13:16])))
out['default_ranking'] = dict(rom='$0B34', ram='$E680 (5 x 16 bytes; hi score $E600 = first 8 bytes)', entries=rank,
                              note='5th name first letter overwritten by region ($0B04): J->$13 A->$0A N->$17')

sc = {}
for k in range(1, 12):
    end = 0x2337 + 8 * k
    sc[str(8 * k)] = bcd8(fx(end - 7, 8))
out['score_table'] = dict(rom='$2337', note='index = enemy field +$15; 8 BCD digits ending at $2337+index; value shown x10',
                          values=sc)

out['strings'] = {k: text_string(a) for k, a in dict(
    oneup=0x06C3, hi=0x06CB, twoup=0x06D2, lives_p1=0x06DA, lives_p2=0x06E1,
    bar_p1=0x19BE, bar_p2=0x19D7, speed_p1=0x19F0, speed_p2=0x1A03, naming_p1=0x1A16, naming_p2=0x1A21,
    continue_p1=0x1D4E, continue_p2=0x1D5D, gameover_p1=0x1D6C, gameover_p2=0x1D7B,
    push_start_a=0x160B, push_start_b=0x1621, push_start_c=0x1633, bonus=0x1646, credit=0x165F, battle=0x166D).items()}

out['item_effects'] = dict(cite='$2657-$275A (switch on item field +$0A)', effects={
    '0x80': 'speed +1 (max 3), sound $1A', '0x81': 'speed -1 (min 1), sound $1B',
    '0x01': 'BIT level +1 (max 3), rebuild orbit', '0x02': 'S.G. level +1 (max 3)', '0x03': 'M.B.L. level +1 (max 2)',
    '0x04': '3WAY level +1 (max 2)', '0x10': 'AUTO := $10', '0x11': 'AUTO := $11',
    '0x06': 'combine into Side Arms robot ($2E4E)', '0x07': 'no effect (collect only)', '0x08': 'extra life, sound $1D'})

dst = ROOT / 'res/generated/player.json'
dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text(json.dumps(out, indent=1))
print(dst)
